In [2]:
import pandas as pd

df = pd.read_csv('../data/input/frota_detran_por_uf_2025.csv', sep=';')
df.head()

     UF  Marca Modelo Ano Fabricação Veículo CRV  Qtd. Veículos
0  ACRE        AGRALE                       1984            1.0
1  ACRE  AGRALE/10000                       2012            9.0
2  ACRE  AGRALE/10000                       2013            4.0
3  ACRE  AGRALE/10000                       2014            4.0
4  ACRE  AGRALE/10000                       2015            3.0

In [3]:
df["Ano Fabricação Veículo CRV"] = pd.to_numeric(
    df["Ano Fabricação Veículo CRV"], errors="coerce"
)

df["Qtd. Veículos"] = pd.to_numeric(
    df["Qtd. Veículos"], errors="coerce"
)

df = df.dropna(subset=["Ano Fabricação Veículo CRV", "Qtd. Veículos"])

df["Ano Fabricação Veículo CRV"] = df["Ano Fabricação Veículo CRV"].astype(int)
df["Qtd. Veículos"] = df["Qtd. Veículos"].astype(int)

In [4]:
df["IMPORTADO"] = df["Marca Modelo"].str.startswith("I/", na=False)

df["Marca Modelo s/ importado"] = df["Marca Modelo"].str.removeprefix("I/")

In [5]:
df["qtd_barras"] = df["Marca Modelo"].str.count("/")

df.loc[df["qtd_barras"] >= 1, "MARCA"] = (
    df.loc[df["qtd_barras"] >= 1, "Marca Modelo s/ importado"]
      .str.split("/")
      .str[0]
)

df["Marca Modelo s/ marca"] = (
    df["Marca Modelo s/ importado"]
      .str.replace(r"^[^/]+/", "", regex=True)
)

In [8]:
brands = ["ALFA ROMEO","JINBEI","LOTUS","D2D","INTERNATIONAL","MARCOPOLO","CHALLENGER","BIMOTA","PIAGGIO","XCMG","MAN","TVS","HAOBAO","CHAMONIX","DAYI","MALAGUTI","DAF","AUDI","YUKI","PORSCHE","KAHENA","BR JINMA","TINBOT","MATRA","HARVESTER","VOLTZ","HYUNDAI","LAMBORGHINI","CF MOTOS","LUQI","SCANIA","GMC","TROLLER","VOLKSWAGEN","GOWEI","SANTA MATILDE","AMAZONAS","MOTOCAR","JOHNNY PAG","SSANGYONG","MOTTU","FIAT ALLIS","FERRARI","CYKLOS","YAMAHA","INDIAN","BUDNY","LEAPMOTOR","GAC GROUP","SEAT","BRANDY","PUMA","SUPER SOCO","MG MOTORS","MANGOSTEEN","AITO","MITSUBISHI","HUSABERG","GEELY","NETA","MAJ","GENESIS","DFM","WUXI-GWS","WATTS","LAND ROVER","MOTRIZ","HUSQVARNA","TALARIA","ORIGEM","UNIVERSAL","HAFEI","ZEEKR","FNM","DAIHATSU","MV AGUSTA","REGAL RAPTOR","JOHN DEERE","KTM","PIONEIRA","FORD","CHRYSLER","HORWIN","CADILLAC","RAM","LEXUS","ENGESA","DENZA","FORA DA FROTA BRASILEIRA","FUTENGDA","ISUZU","ENVEMO","DAELIM","TAILING","NIU","MILETO","RENAULT","EFFA MOTORS","KENWORTH","JIAPENG VOLCANO","SMART","VMOTO","ANAIG","VENTO","BASHI MOTORS","JETOUR","DAYANG","SILENCE","CHANGAN","CASE IH","SANNYA MOTOR","NAO VEICULAR","BEE","MS ELETRIC","SUNDOWN","JAECOO","SUDU","SINO-GOLD","SMARDA","FIBRAVAN","DAMAC","JAGUAR","WAZN","MGW","BRILSTAR","VOLARE","IVECO","FOTON","MORMAII E-MOTORS","BUELL","DUCATI","KIA","BENTLEY","MASSEY FERGUSON","YADEA","MAZDA","HONDA","MAHINDRA","MONTESA 250","BUGRE","LAVRALE","EGO","CAGIVA","LIFAN","MOTO GUZZI","FENDT","DODGE","MVK","FLYELETRICS","XINGYUE","ROLLS-ROYCE","E-MART CAR","BORAM","PONTIAC","KUHN MONTANA","ROTOM","RIVIAN","WEHAWK","FUSCO MOTOSEGURA","GAS GAS","CALOI","BRM","OMODA","IMPLANOR","CAN-AM","LINCOLN","VESPA","CITROEN","MOTORINO","VALTRA","AGRALE","GLOOV","BRAVIA","MAFERSA","ASIA MOTORS","AIMA","WUYANG","HIGER","SUZUKI","JINYI","DAEWOO","AVELLOZ","BULL","NEW HOLLAND","BRILLIANCE","BAJAJ","YANMAR","ARROW MOBILITY S.A","CHANA","IDEAL","DAFRA","ROYAL ENFIELD","MIURA","ZONTES","GURGEL","WALK","CASE","BABY","TESLA","SWM","RIDDARA","HUMMER","STARA","MRX","TRAXX","MASERATI","ANKAI","MOTO MORINI","KYMCO","PETERBILT","AIPAO","SHINERAY","SYM","HYOSUNG","FYM","JAC","NISSAN","SANYANG","MIZA","MINI","PLA PULVERIZADORES","SUBARU","WAKE","ADLY","LEVA MOTORS","IROS","GWM","TOYOTA","LS TRACTOR","JPX","GREEN","HENREY","GREAT WALL MOTOR","CHERY","AUGURI","FANTIC","JACTO","JEEP","MOTO CHEFE","CHEVROLET","SHENGQI","SPARTAN","SERES","RELY","LUYUAN","PEUGEOT","CROSS LANDER","YAMASAKI","LANDINI","JAN","HARLEY-DAVIDSON","BYD","FYBER","DONGFENG","MCLAREN","DEUTZ","VENTANE MOTORS","SOUSA","SINOTRUK","VAMMO MOTOS","TRIUMPH","KAWASAKI","ARIIC","APRILIA","CBT","KASINSKI","AMAZON","GARINNI","WANGPAI","TAC","JIAYUAN","ASTON MARTIN","LADA","LVNENG E-BIKE","BSA","FEVER","SWM MOTORS","BENELLI","SHACMAN","LETIN","BUGATTI","GCX","HAOJIAN","ACURA","IANOR","FIAT","JONNY","BMW","VOLVO","LAFER","HAOJUE","MERCEDES BENZ"]

In [9]:
df_importados = df[df['IMPORTADO']]
df_importados.head()

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca
7090,ACRE,I/AIMA VOLTZ EV01,2019,1,True,AIMA VOLTZ EV01,1,AIMA VOLTZ EV01,AIMA VOLTZ EV01
7091,ACRE,I/AIMA VOLTZ EV01 SPORT,2022,1,True,AIMA VOLTZ EV01 SPORT,1,AIMA VOLTZ EV01 SPORT,AIMA VOLTZ EV01 SPORT
7092,ACRE,I/ALFA ROMEO 156,1998,1,True,ALFA ROMEO 156,1,ALFA ROMEO 156,ALFA ROMEO 156
7093,ACRE,I/AMGC HUMMER H3 SUV,2008,1,True,AMGC HUMMER H3 SUV,1,AMGC HUMMER H3 SUV,AMGC HUMMER H3 SUV
7094,ACRE,I/ASIA TOPIC DLX,1998,2,True,ASIA TOPIC DLX,1,ASIA TOPIC DLX,ASIA TOPIC DLX

In [10]:
# Ordenar marcas por tamanho (maiores primeiro)
brands_sorted = sorted(brands, key=len, reverse=True)

def extrair_montadora(texto):
    for marca in brands_sorted:
        if texto.startswith(marca):
            return marca
    return None

df_importados['MARCA'] = df_importados['Marca Modelo s/ marca'].apply(extrair_montadora)
df_importados.head()

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca
7090,ACRE,I/AIMA VOLTZ EV01,2019,1,True,AIMA VOLTZ EV01,1,AIMA,AIMA VOLTZ EV01
7091,ACRE,I/AIMA VOLTZ EV01 SPORT,2022,1,True,AIMA VOLTZ EV01 SPORT,1,AIMA,AIMA VOLTZ EV01 SPORT
7092,ACRE,I/ALFA ROMEO 156,1998,1,True,ALFA ROMEO 156,1,ALFA ROMEO,ALFA ROMEO 156
7093,ACRE,I/AMGC HUMMER H3 SUV,2008,1,True,AMGC HUMMER H3 SUV,1,NaN,AMGC HUMMER H3 SUV
7094,ACRE,I/ASIA TOPIC DLX,1998,2,True,ASIA TOPIC DLX,1,NaN,ASIA TOPIC DLX

In [ ]:
import re

df_importados['Marca Modelo s/ marca'] = df_importados.apply(
    lambda row: re.sub(
        r'^' + re.escape(row['MARCA']) + r'\s*',
        '',
        row['Marca Modelo s/ marca']
    ) if pd.notna(row['MARCA']) else row['Marca Modelo s/ marca'],
    axis=1
)

In [19]:
df_importados[df_importados['MARCA'].notna()]

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca
7090,ACRE,I/AIMA VOLTZ EV01,2019,1,True,AIMA VOLTZ EV01,1,AIMA,VOLTZ EV01
7091,ACRE,I/AIMA VOLTZ EV01 SPORT,2022,1,True,AIMA VOLTZ EV01 SPORT,1,AIMA,VOLTZ EV01 SPORT
7092,ACRE,I/ALFA ROMEO 156,1998,1,True,ALFA ROMEO 156,1,ALFA ROMEO,156
7096,ACRE,I/AUDI A1 1.4TFSI,2011,2,True,AUDI A1 1.4TFSI,1,AUDI,A1 1.4TFSI
7097,ACRE,I/AUDI A1 1.4TFSI SP,2012,1,True,AUDI A1 1.4TFSI SP,1,AUDI,A1 1.4TFSI SP
...,...,...,...,...,...,...,...,...,...
1262401,TOCANTINS,I/YAMAHA YZF R1,2008,6,True,YAMAHA YZF R1,1,YAMAHA,YZF R1
1262402,TOCANTINS,I/YAMAHA YZF R1,2009,5,True,YAMAHA YZF R1,1,YAMAHA,YZF R1
1262403,TOCANTINS,I/YAMAHA YZF R1,2011,1,True,YAMAHA YZF R1,1,YAMAHA,YZF R1
1262404,TOCANTINS,I/YAMAHA YZF R1,2013,1,True,YAMAHA YZF R1,1,YAMAHA,YZF R1
1262405,TOCANTINS,I/YAMAHA YZF R6,2008,1,True,YAMAHA YZF R6,1,YAMAHA,YZF R6

In [ ]:
df[df['MARCA'] == 'IMP'].head()

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca
9681,ACRE,IMP/ASIA AM825 T,1993,1,False,IMP/ASIA AM825 T,1,IMP,ASIA AM825 T
9682,ACRE,IMP/ASIA AM825 T,1997,1,False,IMP/ASIA AM825 T,1,IMP,ASIA AM825 T
9683,ACRE,IMP/ASIA HI-TOPIC,1995,4,False,IMP/ASIA HI-TOPIC,1,IMP,ASIA HI-TOPIC
9684,ACRE,IMP/ASIA TOPIC,1996,1,False,IMP/ASIA TOPIC,1,IMP,ASIA TOPIC
9685,ACRE,IMP/ASIA TOWNER COACH,1994,1,False,IMP/ASIA TOWNER COACH,1,IMP,ASIA TOWNER COACH

In [21]:
mask_imp = df['MARCA'] == 'IMP'

df.loc[mask_imp, 'IMPORTADO'] = True

In [22]:
df.loc[mask_imp, 'MARCA'] = (
    df.loc[mask_imp, 'Marca Modelo s/ marca']
    .apply(extrair_montadora)
)

In [23]:
df.loc[mask_imp, 'Marca Modelo s/ marca'] = (
    df.loc[mask_imp]
    .apply(
        lambda row: re.sub(
            r'^' + re.escape(row['MARCA']) + r'\s*',
            '',
            row['Marca Modelo s/ marca']
        ) if pd.notna(row['MARCA']) else row['Marca Modelo s/ marca'],
        axis=1
    )
)

In [24]:
df.loc[mask_imp]

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca
9681,ACRE,IMP/ASIA AM825 T,1993,1,True,IMP/ASIA AM825 T,1,NaN,ASIA AM825 T
9682,ACRE,IMP/ASIA AM825 T,1997,1,True,IMP/ASIA AM825 T,1,NaN,ASIA AM825 T
9683,ACRE,IMP/ASIA HI-TOPIC,1995,4,True,IMP/ASIA HI-TOPIC,1,NaN,ASIA HI-TOPIC
9684,ACRE,IMP/ASIA TOPIC,1996,1,True,IMP/ASIA TOPIC,1,NaN,ASIA TOPIC
9685,ACRE,IMP/ASIA TOWNER COACH,1994,1,True,IMP/ASIA TOWNER COACH,1,NaN,ASIA TOWNER COACH
...,...,...,...,...,...,...,...,...,...
1263105,TOCANTINS,IMP/YAMAHA BWS,1995,4,True,IMP/YAMAHA BWS,1,YAMAHA,BWS
1263106,TOCANTINS,IMP/YAMAHA FZR 600,1990,1,True,IMP/YAMAHA FZR 600,1,YAMAHA,FZR 600
1263107,TOCANTINS,IMP/YAMAHA TDM 850,1998,2,True,IMP/YAMAHA TDM 850,1,YAMAHA,TDM 850
1263108,TOCANTINS,IMP/YAMAHA VIRAGO,1995,1,True,IMP/YAMAHA VIRAGO,1,YAMAHA,VIRAGO
1263109,TOCANTINS,IMP/YAMAHA XV 1100,1995,1,True,IMP/YAMAHA XV 1100,1,YAMAHA,XV 1100

In [25]:
df['ARTESANAL'] = df['MARCA'].str.startswith('A.', na=False)

In [27]:
df.dropna(subset=['MARCA'], inplace=True)

In [28]:
resumo = df[(~df['ARTESANAL'])].groupby("MARCA")["Qtd. Veículos"].sum()
marcas_validas = resumo[resumo > 10]

df_final = df[df['MARCA'].isin(marcas_validas.index)]
df_final = df_final.dropna(subset=['MARCA'])
df_final.head()

,UF,Marca Modelo,Ano Fabricação Veículo CRV,Qtd. Veículos,IMPORTADO,Marca Modelo s/ importado,qtd_barras,MARCA,Marca Modelo s/ marca,ARTESANAL
1,ACRE,AGRALE/10000,2012,9,False,AGRALE/10000,1,AGRALE,10000,False
2,ACRE,AGRALE/10000,2013,4,False,AGRALE/10000,1,AGRALE,10000,False
3,ACRE,AGRALE/10000,2014,4,False,AGRALE/10000,1,AGRALE,10000,False
4,ACRE,AGRALE/10000,2015,3,False,AGRALE/10000,1,AGRALE,10000,False
5,ACRE,AGRALE/13000,2008,11,False,AGRALE/13000,1,AGRALE,13000,False

In [31]:
df_final.groupby('IMPORTADO')['Qtd. Veículos'].sum()

IMPORTADO
False    113085457
True      10762933
Name: Qtd. Veículos, dtype: int64

In [32]:
columns = ['UF', 'MARCA', 'Marca Modelo', 'Marca Modelo s/ marca', 'Ano Fabricação Veículo CRV', 'Qtd. Veículos', 'IMPORTADO']
columns_map = {
    'UF': 'uf',
    'MARCA': 'marca',	
    'Marca Modelo s/ marca': 'modelo',
    'Ano Fabricação Veículo CRV': 'ano_fabricacao',
    'Qtd. Veículos': 'frota',
    'Marca Modelo': 'descricao_detran',
    'IMPORTADO': 'importado'
}

df_final = df_final[columns].rename(columns=columns_map)

# LOAD df_final as detran_vehicle_norm

In [33]:
df_final.head()

     uf   marca descricao_detran modelo  ano_fabricacao  frota  importado
1  ACRE  AGRALE     AGRALE/10000  10000            2012      9      False
2  ACRE  AGRALE     AGRALE/10000  10000            2013      4      False
3  ACRE  AGRALE     AGRALE/10000  10000            2014      4      False
4  ACRE  AGRALE     AGRALE/10000  10000            2015      3      False
5  ACRE  AGRALE     AGRALE/13000  13000            2008     11      False